### ISSUE TITLE
YouTube not working?

### ISSUE THREAD

**Issue by faveoled** [Altonss/org.x.hypnotix#2]
![image](https://github.com/Altonss/org.x.hypnotix/assets/85760289/69774498-c971-4a22-895d-4c22797295db)
Not quite sure how to watch YT there but this seems to be an issue

**Comment by Altonss** [comment]
Youtube works perfectly fine for me (yt-dlp is shipped with the flatpak build), so it's only an "issue" with the display in the settings.
Please try it out before opening an issue :)
