### ISSUE TITLE
Missing icon in help

### ISSUE THREAD

**Issue by faveoled** [Altonss/org.x.hypnotix#3]
![image](https://github.com/Altonss/org.x.hypnotix/assets/85760289/980f353c-dc6d-4639-bfb6-c3993235f912)
Red square should likely be replaced with an icon.
Also in logs:
```
[Errno 2] No such file or directory: '/app/hypnotix/share/common-licenses/GPL'
```

**Comment by Altonss** [comment]
This should be fixed now :)
